name: dev-terraform-cicd
on:
  push:
    branches:
    - 'feature/**'
    - 'bugfix/**'
    
jobs:
  terraform-cicd:
    uses: ./.github/workflows/reusable.terraform-cicd.yml
    secrets: inherit
    with:
      varFilePath: ./.github/variables/newrelic.env
      environment: dev
      is_apply: false
